"""UserEvent: one raw behavioural event from the target application.

Deliberately minimal. It records *what happened, when, in which anonymous
session* — never who the user is. Fields for component IDs or UI Spec versions
are added when those concepts exist (telemetry pipeline, later step).
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, String, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, validates

from darwin.db.base import Base


class UserEvent(Base):
    __tablename__ = "user_event"
    __table_args__ = (
        CheckConstraint("event_type <> ''", name="event_type_not_empty"),
        CheckConstraint("jsonb_typeof(payload) = 'object'", name="payload_is_object"),
        # Signal reconciliation reads one session's events, ordered by
        # occurred_at, after every accepted event. Without this index that is a
        # full-table scan.
        Index("ix_user_event_session_id_occurred_at", "session_id", "occurred_at"),
        CheckConstraint(
            "ui_generation IS NULL OR ui_generation BETWEEN 0 AND 100000",
            name="ui_generation_in_range",
        ),
        CheckConstraint(
            "ui_spec_hash IS NULL OR ui_spec_hash ~ '^[0-9a-f]{64}$'", name="ui_spec_hash_is_sha256"
        ),
    )

    # Server-owned identity; other tables will reference this, never client input.
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)

    # Client-generated idempotency key. UNIQUE makes a redelivered event a
    # no-op instead of a duplicate row (SQS delivers at least once).
    event_id: Mapped[uuid.UUID] = mapped_column(unique=True)

    # e.g. "click", "form_submit". Free text until the telemetry step defines
    # the vocabulary; a PostgreSQL ENUM would make every new type a migration.
    event_type: Mapped[str] = mapped_column(String(64))

    # Random, pseudonymous per-visit identifier generated by the SDK.
    # Not a user ID, email, or device fingerprint.
    session_id: Mapped[uuid.UUID]

    # When it happened (client clock) vs. when we stored it (server clock).
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # UI attribution (Step 15, migration 0011). What the client SAYS it rendered —
    # a generation number and a spec hash — plus the server-verified spec version:
    # set only when the claimed ui_spec_version_id exists and its content hash equals
    # the claimed hash. NULL = unknown (every event before Step 15 stays unknown; it is
    # never backfilled). Claims are never used for authorization.
    ui_generation: Mapped[int | None]
    ui_spec_hash: Mapped[str | None] = mapped_column(String(64))
    ui_spec_version_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("ui_spec_version.id"))

    # Event-specific, non-personal details (e.g. click coordinates).
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, default=dict, server_default=text("'{}'::jsonb")
    )

    @validates("occurred_at")
    def _require_timezone(self, _key: str, value: datetime) -> datetime:
        # A naive datetime is ambiguous ("12:00 where?"); refuse it at the boundary.
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("occurred_at must be timezone-aware")
        return value
