"""UserEvent: one raw behavioural event from the target application.

Deliberately minimal. It records *what happened, when, in which anonymous
session* — never who the user is. Fields for component IDs or UI Spec versions
are added when those concepts exist (telemetry pipeline, later step).
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, String, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, validates

from darwin.db.base import Base


class UserEvent(Base):
    __tablename__ = "user_event"
    __table_args__ = (
        CheckConstraint("event_type <> ''", name="event_type_not_empty"),
        CheckConstraint("jsonb_typeof(payload) = 'object'", name="payload_is_object"),
    )

    # Server-owned identity; other tables will reference this, never client input.
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)

    # Client-generated idempotency key. UNIQUE makes a redelivered event a
    # no-op instead of a duplicate row (SQS delivers at least once).
    event_id: Mapped[uuid.UUID] = mapped_column(unique=True)

    # e.g. "click", "form_submit". Free text until the telemetry step defines
    # the vocabulary; a PostgreSQL ENUM would make every new type a migration.
    event_type: Mapped[str] = mapped_column(String(64))

    # Random, pseudonymous per-visit identifier generated by the SDK.
    # Not a user ID, email, or device fingerprint.
    session_id: Mapped[uuid.UUID]

    # When it happened (client clock) vs. when we stored it (server clock).
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Event-specific, non-personal details (e.g. click coordinates).
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, default=dict, server_default=text("'{}'::jsonb")
    )

    @validates("occurred_at")
    def _require_timezone(self, _key: str, value: datetime) -> datetime:
        # A naive datetime is ambiguous ("12:00 where?"); refuse it at the boundary.
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("occurred_at must be timezone-aware")
        return value
