"""Telemetry ingestion: turn one validated event into at most one stored row.

This function is the processing boundary. Today it persists synchronously.
Later it is where an event is handed to a queue instead; the HTTP route and
the public schemas do not change (see docs/DATA_PIPELINES.md).
"""

import logging

from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from darwin.db.models import UserEvent
from darwin.telemetry.schemas import IngestionResult, TelemetryEvent

logger = logging.getLogger(__name__)


def ingest_event(session: Session, event: TelemetryEvent) -> IngestionResult:
    """Store ``event`` idempotently. This function owns the transaction.

    One statement does the whole job, so there is no check-then-insert race:

        INSERT INTO user_event (...) VALUES (...)
        ON CONFLICT (event_id) DO NOTHING
        RETURNING id

    If another request already stored this event_id (even one committing at
    this very moment), PostgreSQL's UNIQUE constraint makes the insert a
    no-op and RETURNING yields no row. The first delivery wins; a duplicate
    never overwrites it.
    """
    statement = (
        insert(UserEvent)
        .values(
            event_id=event.event_id,
            event_type=event.event_type,
            session_id=event.session_id,
            occurred_at=event.occurred_at,
            payload=event.payload,
            # id: generated by the model's default; received_at: by PostgreSQL (now()).
        )
        .on_conflict_do_nothing(index_elements=[UserEvent.event_id])
        .returning(UserEvent.id)
    )

    # BEGIN ... COMMIT; any exception rolls back and propagates (-> HTTP 500).
    with session.begin():
        inserted_id = session.execute(statement).scalar_one_or_none()

    result = IngestionResult(
        event_id=event.event_id,
        status="accepted" if inserted_id is not None else "duplicate",
    )
    # Deliberately no payload and no session_id in logs.
    logger.info(
        "telemetry event ingested",
        extra={
            "context": {
                "event_id": str(event.event_id),
                "event_type": event.event_type,
                "status": result.status,
            }
        },
    )
    return result
